apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.metadata.namespace }}
data:
  appsettings.Production.json: |-
    {
      "Logging": {
        "LogLevel": {
            "Default": "Warning",
            "Microsoft.AspNetCore": "Warning",
            "Microsoft.AspNetCore.Hosting.Diagnostics": "Information",
            "Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware": "Information",
            "System.Net.Http.HttpClient": "Warning"
        }
      },
      "ConnectionStrings": {
        "Postgres": {{ .Values.configuration.connectionStrings.postgres | quote }}
      },
      "MessagingBroker": {
          "RabbitMq": {
            "HostName": {{ .Values.configuration.messagingBroker.rabbitMq.hostName | quote }},
            "Port": {{ .Values.configuration.messagingBroker.rabbitMq.port }},
            "UserName": {{ .Values.configuration.messagingBroker.rabbitMq.userName | quote }},
            "Password": {{ .Values.configuration.messagingBroker.rabbitMq.password | quote }},
            "VirtualHost": {{ .Values.configuration.messagingBroker.rabbitMq.virtualHost | quote }},
              "Ssl": {
                  "Enabled": {{ .Values.configuration.messagingBroker.rabbitMq.ssl.enabled }}
              }
          }
      }
    }
